name: Commit Message Lint

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install commitlint
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
      - name: Run commitlint
        run: |
          commitlint --from=HEAD~1 --to=HEAD
